apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: this is a very very very long name for a workflow and it is possible and hte UI is messed up "·$%"·$%"·$%"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world 25"
